### ISSUE TITLE
orbit controls ...

### ISSUE THREAD

**Issue by dirkk0** [polygonjs/polygonjs#47]
... don't work for me, in both examples start.html and start2.html.

Great idea and implementation, nevertheless!
Thanks, Dirk

**Comment by frading** [comment]
Thanks a lot for the heads up, those don't work for me either. I indeed broke something, will look into it asap.

And thanks a lot for the kind words, I really appreciate.

**Comment by frading** [comment]
It is now fixed. The problem was that the camera was not completely computed when creating the viewer, so I now make sure it is with https://github.com/polygonjs/polygonjs/blob/020a792061e85e77c533406586224d55f5779270/src/engine/nodes/obj/_BaseCamera.ts#L324

Closing this, but thanks a lot again for letting me know.
