### ISSUE TITLE
wrong link in the docs

### ISSUE THREAD

**Issue by rozek** [polygonjs/polygonjs#63]
"https://polygonjs.com/docs/install/add" exists, but if you click on the link which should navigate to the next chapter in the docs (namely "https://polygonjs.com/docs/export"), that page is missing...

**Comment by rozek** [comment]
...which is strange since "https://polygonjs.com/docs/export" seems to exist

**Comment by frading** [comment]
Interesting, I've just tested this, and it works fine on
- chrome and firefox on linux
- firefox on android

but I see some weird behavior on safari on iOS, where some links need 2 clicks to go to their url, especially after having clicked a first link. Would that be the same browser/OS you've seen this error on?

**Comment by rozek** [comment]
I've used Brave (a Chrome-based browser) on macOS

**Comment by frading** [comment]
It seems like the issue with those links was due to some CSS not being handled well, at least from my iphone. I've deployed a fix now. Upgrade to 1.5.29-2 if you want to see this locally.

I could not reproduce the bug on Brave+mac though, so the reason may be different there. Curious to know if you still observe the same problem.

**Comment by rozek** [comment]
I just tried again - and it worked. Thank you very much for your effort!
