### ISSUE TITLE
How to import a scene into a plain HTML document?

### ISSUE THREAD

**Issue by rozek** [polygonjs/polygonjs#66]
Hello,

I may be blind but I could not find instructions for exporting a scene such that I can easily import it into a plain web page, e.g. similar to

```
  ...
  <div id="xxx" style="..."></div>
  <link rel="stylesheet" href="xxx.css"/>
  <script src="xxx.js"></script>
  ...
```

The script would not need editor functionality, a simple "player" would suffice

**Comment by rozek** [comment]
Well, I just found that an online export to Vanilla JS comes close to what I have in mind - but, of course, I do not want to save my project in the cloud if a local save would suffice. So, how do I achieve a local export to Vanilla JS?

**Comment by frading** [comment]
Sorry about this, it's most likely that I need to improve the documentation, and especially the bugs you've encountered, as they add to the confusion.

And importing a scene into a plain HTML is one of the recommended use of polygonjs, so it should be ultra clear how to do so. It's clearly not the case, so I'll work on it. But for now here are the steps below. You already know most of them, so they're all here together completion's sake.

1. Start by creating a project with the scaffolding cli tool. In this case, make sure to create a new project, to pick up the last version 1.5.27-2, as I've just published an update.

> `yarn create polygonjs`

You'll then see a prompt to pick a project name.

2. Then you have a choice to use any of the 5 available templates:
❯   Vanilla
    Three
    Vue
    React
    React Three Fiber

In this case, pick `Vanilla`.

3. Then select javascript or typescript. My personal recommendation is typescript, but that's up to your preference.

4. When the project is installed, you'll see instructions. Follow the first one, to go in the project and install the dependencies with `cd your-project && yarn`

5. Start the editor with `yarn polygon`

6. Open the default scene at `http://localhost:8091/scenes/scene_01/edit`, simply save it with File->Save or Ctrl+S (make sure to leave the File->Export setting OFF).

7. Start the dev server with `yarn dev`, and open it on `http://localhost:5173` (it may end up on a different port like 5174, double check the output of yarn dev)

8. You'll see your scene inside your html page. And you can see the html in your project folder at the root `index.html`. If you had used a framework like vue or react, it would be under the `src` folder at `src/index.html`.

From now, every time you save your scene, the dev server will reload, and you'll see the page update. For instance, hide the sphere by toggling off the display flag of the node `geo1` (the display flag is the blue vertical line on its right), and save your scene again. As soon as you save, the html reloads and picks up your changes.

Similarly, you can edit the index.html, and the dev server will reload.

9. If you want to output a build, you can run `yarn build`, and this will export only the html,js,css you need in the `dist` folder.

If you want to dive further, you can also edit `src/main.ts` (or `src/main.js`), and update how the scene is loaded. It's just 2 lines of js. You can also use this file to add your own js, load multiple scenes, use the [js api](https://polygonjs.com/docs/api).

**Comment by rozek** [comment]
Wow, **that was _really_ helpful**! Thank you very much for your effort!

`yarn` worked like a charm (I'll double-check the problems I mentioned in my other issues as well), `yarn dev` reloads after every save (great!) and `yarn build` exports the files I need for imports into a web page.

I'm a bit surprised by the names of the files in the `assets` folder, though (which seem to be unpredictable and change after every modification I make to the scene)

I also don't see how to import multiple Polygon.JS scenes into the same web page?

**Comment by frading** [comment]
Cool! Glad that worked. And thank you for your patience, as I know how frustrating it can be to encounter so many issues as you try a new tool.

And yes, the build files are designed to be generated with unique names. The reason is that it avoids cache issues once deployed on a server. If they kept the same name, you could end up in some situations where some old files are cached by a user's browser, and some are not, leading to a site that doesn't work and it's hard to tell why. Note that this behavior is not driven by Polygonjs, but by vite, which is the javascript bundler used in the scaffolded project. Actually, it's the standard and most bundler would use the same method.

This means that any modification should be done before creating the production build.

And you can do so by modifying any file in the project, except the ones in the autogenerated folder. Those are the only files that will be replaced by the editor when you save your scene.

So What you see in `main.js` is just a default starting point. You can modify this file in any way you like. In fact, it's strongly encourage to modify it, I've done so in every single project I've delivered.

I've just created this repository ( https://github.com/polygonjs/vanilla-example ) to better illustrate how to. Have a look specifically at this commit ( https://github.com/polygonjs/vanilla-example/commit/9bb20272049e02ca5c0c9067cad5644f6205340c ), which shows the modifications to index.html, style.css and main.ts. 

As for poster.png, yes, it's not updated when you save a scene. Otherwise, it may be updated when you don't mean to. Instead, it's either created a first time when the file does not exist yet, and after that you need to click on the camera icon above the 3D viewer.

![image](https://github.com/polygonjs/polygonjs/assets/59701/89092e89-45e8-4924-82c7-74ee4100b23d)

Feel free to let me know more about your use case if you think this whole process doesn't fit your worflow.

**Comment by frading** [comment]
Good idea for linking to the commit, I've added a link to the most important one, but let me know if you could do with more explanations.

For the poster.png, you should see a message in the status bar at the bottom of the editor, saying where the image has been saved. You shouldn't have to click on the download button (or if you do see the image being downloaded by the browser into your Downloads folder without clicking on it, let me know). Actually, this button probably adds confusion, so I'll hide it when using the local version.

![image](https://github.com/polygonjs/polygonjs/assets/59701/e8b66769-820e-4669-a053-a8139f3b0dc6)

**Comment by rozek** [comment]
Indeed, there is a message in the status bar, but

* without explicitly mentioning it, I did not recognize,
* its difficult to read (low contrast)
* it **vanishes after a few seconds** - which makes it almost impossible for me (and, perhaps, others) to read the full path (it's really long on my machine, although I now know where to look on the file system)

**Comment by rozek** [comment]
In my opinion, the link to the commit mentioned above and the words you wrote are absolutely sufficient for the moment - assuming, that there are many more (and more important) issues to solve.

Thank you very much for your effort!

**Comment by frading** [comment]
Yes, thank you for making those points regarding the poster and I completely agree. I'll have a think on how to make that clearer, it should be available in next release.

**Comment by frading** [comment]
The image and video capture notifications now look like this:

![image](https://github.com/polygonjs/polygonjs/assets/59701/aa2520d1-0103-45a9-9b48-4ac1465f0a92)

![image](https://github.com/polygonjs/polygonjs/assets/59701/342360c6-c266-44cc-bfc5-38fc983f5638)

And the link will open the image in your browser in full page. So I believe it should be clear what has been done (that the image/video was captured and placed inside the project in a pre-defined location) and that there is no further action required.

And to go back to your questions about build files having different names like `assets/index-xxx.js`, I realise after replying that the name wasn't changing in the previous export method used to upload to Webflow. So now that I've updated this upload method, using the `yarn build_s3` command will create build files that will not change, and will be like `assets/index.js`. This is indeed very important so that the [embed code](https://polygonjs.com/docs/integrations/s3) that you would copy/paste to webflow doesn't have to updated. That may not be your use case, but if you really need non changing names, that's one way to have them.

Or if you want the same behavior without files being uploaded anywhere, you can edit the `vite.config.js` file, with the [same modifications](https://github.com/polygonjs/create-polygonjs-utils/blob/main/src/s3/buildCommon.ts#L38) that can be seen in the upload tool, which are here as well for clarity:

```
build: {
	manifest: true,
	rollupOptions: {
		output: {
			entryFileNames: \`assets/[name].js\`,
			chunkFileNames: \`assets/[name].js\`,
			assetFileNames: \`assets/[name].[ext]\`,
		},
	},
},
```
and the `vite.config.js` wasn't created in the previous templates, but it is now, so you'll find it if you create a new project.

Closing this now, as I believe this answers all your questions, but feel free to re-open if not. Although I encourage you to keep 1 question per issue if possible.
