### ISSUE TITLE
"THREE.EXRLoader: provided file doesn't appear to be in OpenEXR format."

### ISSUE THREAD

**Issue by rozek** [polygonjs/polygonjs#67]
Yet another problem: given the outcome of my previous issue, I tried to "online export" the demo scene to "Vanilla JS" from my locally installed PolygonJS project.

The codesandbox.io window opened (with the expected set of files) but failed to show the scene - instead I got the following error message:

```
THREE.EXRLoader: provided file doesn't appear to be in OpenEXR format.

▼ 4 stack frames were expanded.
parseHeader
https://lnwx6t.csb.app/node_modules/three/examples/jsm/loaders/EXRLoader.js:1142:15
EXRLoader.parse
https://lnwx6t.csb.app/node_modules/three/examples/jsm/loaders/EXRLoader.js:1286:23
Object.eval [as onLoad]
https://lnwx6t.csb.app/node_modules/three/build/three.cjs:41908:26
eval
https://lnwx6t.csb.app/node_modules/three/build/three.cjs:41502:38
▲ 4 stack frames were expanded.

This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```

**Comment by frading** [comment]
I realise now this happens when you export to codesandbox using the default scene, on a local install.

The reason is that the textures are only local (the env map url is `textures/piz_compressed.exr` ), and are not uploaded to codesandbox, which then fails to read them and throws and error.

But if you were to try and export the online demo scene from https://polygonjs.com/demo, then the export to codesandbox works as expected (the env map url is already online, at `https://raw.githubusercontent.com/polygonjs/polygonjs-assets/master//textures/piz_compressed.exr` ).

I'll have a think if I should deactivate those exports when local assets are in use in the scene, or find a way to upload local assets to codesandbox.

**Comment by frading** [comment]
It seems that uploading local assets to codesandbox requires authentication, and there would be storage to account. So I aim to keep this simple for now. I've updated the export panel for when local assets are present in the scene, which displays a clearer warning, and disables the export buttons. It's available in `1.5.29-3`.

![image](https://github.com/polygonjs/polygonjs/assets/59701/a63f3179-b17a-4e19-9df3-300eec137793)

**Comment by rozek** [comment]
Just not to remain silent: thank you very much for your effort!

Right now, I'm working on some AI projects which bind my time - as a consequence, I'll not be able to check your changes and continue working with PolygonJS for the moment.

I'll come back to you as soon as I'll find some spare time...

Anyway: good luck and good success for your work!

**Comment by frading** [comment]
My pleasure. And no worries at all of course. I really appreciate the time you took to put together those bug reports.
