### ISSUE TITLE
Run polygon.js as a webhook in response and return a message and an attachment

### ISSUE THREAD

**Issue by fire** [polygonjs/polygonjs#68]
I recently woke up from a nap with an idea to use PolygonJS as a Discord webhook watcher. The goal is to output a "Hello World" message along with a GLTF cube. Alternatively, I would like it to send an OpenAI LLM message and an AI-generated image as an attachment via Replicate.com.

I have already set up the API endpoints for the cloud APIs. However, I am seeking insights on setting up the Discord webhook that ticks every half second, and advice on cloud hosting.

**Comment by frading** [comment]
Here is a [small repo](https://github.com/frading/polygonjs_tick_example) you could start from. It's scaffolded with `yarn create polygonjs` and the vanilla js template. I've then updated `main.js` to [add a callback on every tick](https://github.com/frading/polygonjs_tick_example/commit/e405802cd5166dcd193a26cb88ac6ef5f66fee24). Then inside, you just need to check if you've pinged more than 1 second ago, and do the ping if that's the case.

Adding here as well for clarity.
```
const loadedData = await fetchSceneAndMount_scene_01({
	domElement: 'app',
	baseUrl: import.meta.env.BASE_URL,
});
const scene = loadedData.scene;
let lastPingAt = -1;

// add a callback that will be called on each tick
scene.registerOnBeforeTick('my-callback', () => {
	const currentTime = scene.time();
	const timeSinceLastPing = scene.time() - lastPingAt;
	// if the last ping was more than 1 second ago, then ping
	if (timeSinceLastPing > 1) {
		lastPingAt = currentTime;
		console.log('ping');
	}
});
```

Then for hosting, netlify is super easy to setup. Just link your repo into your netlify account, and it will build it and deploy it. You should have to configure anything. Otherwise, you can also deploy straight to aws s3 if you're familiar with it, I've just added a [tutorial](https://polygonjs.com/docs/integrations/s3) about this.

Let me know if that helps. I'd be curious to see what you end up with. And I'll leave this issue open for a bit, but I encourage you to ask questions in the [forum](https://forum.polygonjs.com/).

**Comment by fire** [comment]
For your sample code can you either choose CC0 or match the polygonjs license?

**Comment by frading** [comment]
Sure, just added MIT license

**Comment by fire** [comment]
About the s3 sample, I expect it will work with digital ocean's spaces which is s3 compatible. Making a note.

**Comment by frading** [comment]
I haven't used digital ocean's spaces, so can't be sure, but that'd be nice to see. This is the code that takes care of the upload: https://github.com/polygonjs/create-polygonjs-utils/blob/main/src/s3/uploadCommon.ts.

**Comment by fire** [comment]
Serverless postgress will enable me to store past configurations, like and dislikes. As far as I can it's merely a node-postgres (npm) fork.

https://neon.tech/blog/serverless-driver-for-postgres

I spent the morning writing a plan.

https://v-sekai.github.io/manuals/decisions/20231109-discord-polygonjs-generator.html

**Comment by frading** [comment]
Thank you for the links, and very curious to see where this will go.
