### ISSUE TITLE
COP Node "Text" doesn't update on changes

### ISSUE THREAD

**Issue by milangress** [polygonjs/polygonjs#73]
I'm still really new to polygonjs…  Still wrapping my head around it, so maybe I overlooked something. 
polygonjs is so awsome btw! <3

I was working with the [COP Node Text](https://github.com/polygonjs/polygonjs/blob/master/src/engine/nodes/cop/Text.ts) that produces a canvas that can be used as a texture. Some of the settings do not update the canvas, or they update the canvas, but polygonjs does not show the change in the texture.

Digging around, I found the COP Canvas Node that has a button to manually update the texture. 
Maybe the same button would make sense for the text node?

https://github.com/polygonjs/polygonjs/blob/a982392fe947c49fdbd2c3c95ddc9b8511e520ba/src/engine/nodes/cop/Canvas.ts#L19-L23

**Comment by frading** [comment]
@milangress Thanks a lot for the kind words and for digging into this, that's super helpful.

Which parameter changes have you found that do not update as expected? I've just tested by updating the `text` parameter, and that seems to update fine, so I assume the problems is about other ones.

I've done a minimal setup that shows it updating, if you press play and moves the cursor on and off the cube. Feel free to take this as a starting point to create a minimal repro of the issue.
https://polygonjs.com/gui/cop_text_update_on_change/edit


https://github.com/polygonjs/polygonjs/assets/59701/f3243165-35ba-4e68-b8de-1bc2cd6f7503

There are a couple gotchas, though, for which I could do a better job at documenting:
- the background by default will be fully transparent if the alpha is 0, and will therefore remain black. If you do want the color to be seen, make to sure increase the alpha.
- ideally, setting the alpha to a value lower than 1 should create a transparent texture, but that's currently not the case. The reason is that the text is created using the 2d context of a canvas and not a webgl context, and I believe a 2d context does not handle alpha. So there's definitely room for improvement there, and that could add confusion to help diagnose any problem with this node.
- There's an outstanding issue for every texture node, which is that some parameters change require a full page reload. This is the case for `anisotropy`, and I believe also the min and mag filters. That may also be the case for the params under the `tadvanced` toggle.

Also, the reason the `cop/canvas` node needs an `update` parameter is that the canvas could potentially be updated outside of polygonjs. That's actually the main use of this node. For instance, if you were have a separate code that would allow drawing on the canvas, polygonjs would not know about it, and the texture could not be updated. If that was the case, you would need to trigger the update parameter, using something like `scene.node('/cop/canvas1').p.update.pressButton()`. This then tells polygonjs to reload the texture.

The updating logic is a little different for the `cop/text` node, as the canvas is only used internally to generate the text, and cannot be updated otherwise. So changes are easier to detect, as it can only be done via the parameters. In which case, if a parameter does not trigger a texture change, that can indeed be considered a bug.

I hope that clarifies a bit more about how this currently more internally. Let me know if not, and feel free to expand on which parameters you saw the issue.

**Comment by milangress** [comment]
Thank you so much for your clearly written and in depth answer!
My project files had a lot going on, so maybe I got a bit confused. And indeed there were other problems :)

Trying to reproduce my specific behaviour in your minimal example is possible by changing the resolution. I must have miskicked and scaled one side to from 256 → 257. Then you can see how most sliders stop working. Then changing, for example, `tminFilter` updates the texture and all the sliders work as expected. 

Although to be honest, that really feels like an expected behaviour, :D I just had a bug that would change the texture in unexpected ways. Under normal circumstances, the resolution probably does not change that often.

**Comment by frading** [comment]
ah yes, I've just changed the resolution from `256x256` to `128x256`, and then `64x256`, and the texture seems to be updated in only part of it, which displays this:

![image](https://github.com/polygonjs/polygonjs/assets/59701/f0eedee7-df00-44d1-b146-c4ce299a01a9)

So yes, something's indeed off, I'll take a proper look.

And as you say, changing the resolution doesn't happen very often, and most likely will not happen once the scene is live, which is why I haven't spent much time on getting that right. And even in the editor, once you know it can be fixed with a page reload, it's sort of acceptable. But it's nevertheless confusing the first time you encounter that, so thanks a lot for finding this bug and reporting it.
